project:
  type: website

website:
  title: "Real World Data Science"
  image: images/rwds-logo-150px.png
  favicon: images/rwds-favicon.png
  twitter-card:
    site: "@rwdatasci"
  open-graph: true
  site-url: https://realworlddatascience.net/
  repo-url: https://github.com/realworlddatascience/realworlddatascience.github.io
  repo-actions: [edit, issue]
  body-footer: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    logo: images/rwds-logo-150px.png
    logo-alt: "Real World Data Science brand"
    title: false
    collapse-below: lg
    right:
      - case-studies/index.qmd
      - ideas/index.qmd
      - careers/index.qmd
      - viewpoints/index.qmd
      - text: "About RWDS"
        menu: 
        - text: "Who we are"
          href: about-rwds.qmd
        - text: "How to contribute"
          href: contributor-docs/call-for-contributions.qmd
        - text: "Code of conduct"
          href: CODE_OF_CONDUCT.md
        - text: "Contact us"
          href: contact.qmd
  sidebar: 
    - title: "About us"
      contents:
        - about-rwds.qmd
        - viewpoints/editors-blog/posts/2022/10/18/meet-the-team.qmd
        - rwds-partners.qmd
        - contact.qmd
        - ts-and-cs.qmd
        - CODE_OF_CONDUCT.md
        - LICENCE.md
    - title: "Call for contributions"
      contents:
        - contributor-docs/call-for-contributions.qmd
        - contributor-docs/case-studies.qmd
        - contributor-docs/explainers.qmd
        - contributor-docs/exercises.qmd
        - contributor-docs/datasets.qmd
        - contributor-docs/training-guides.qmd
        - contributor-docs/recommender.qmd
        - contributor-docs/datasciencebites.qmd
        - contributor-docs/contributor-guidelines.qmd
        - contributor-docs/style-guide.qmd
    - title: "Careers"
      contents:
        - careers/index.qmd
        - careers/career-profiles/index.qmd
    - title: "Ideas"
      contents:
        - ideas/index.qmd
        - ideas/tutorials/index.qmd
        - ideas/datasciencebites/index.qmd
    - title: "Viewpoints"
      contents: 
        - viewpoints/index.qmd
        - viewpoints/editors-blog/index.qmd
        - viewpoints/interviews/index.qmd
        - href: viewpoints/newsletter/index.qmd
          text: Newsletter

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    left: |
      [Copyright &copy; 2024 Royal Statistical Society](/LICENCE.md)
    center:
      - href: https://github.com/realworlddatascience
        icon: github
        aria-label: GitHub
      - href: https://zenodo.org/communities/realworlddatascience
        text: "{{< ai zenodo size=2xl >}}"
        aria-label: RWDS Zenodo community
      - href: https://www.linkedin.com/showcase/rss-real-world-data-science
        icon: linkedin
        aria-label: LinkedIn
      - href: https://twitter.com/rwdatasci
        icon: twitter-x
        aria-label: Twitter/X
      - href: https://fosstodon.org/@rwdatasci
        icon: mastodon
        aria-label: Mastodon
      - href: feeds.html
        icon: rss
        aria-label: RWDS rss

    right: |
      [Terms & Conditions](/ts-and-cs.qmd)

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
