project:
  type: website

website:
  title: "Mikkel Roald-Arbøl"
  image: images/rwds-logo-150px.png
  favicon: images/rwds-favicon.png
  twitter-card:
    site: "@roaldarbol"
  open-graph: true
  site-url: https://roald-arboel.com
  repo-url: https://github.com/roaldarbol/quarto-website
  repo-actions: [issue]
  body-footer: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    logo: images/rwds-logo-150px.png
    logo-alt: "Mikkel Roald-Arbøl"
    title: false
    collapse-below: lg
    right:
      - research/index.qmd
      - blog/index.qmd
      - text: "About"
        menu:
        - text: "Who we are"
          href: about.qmd
        - text: "Contact me"
          href: contact.qmd
  sidebar:
    - title: "About"
      contents:
        - about.qmd
        - contact.qmd
        - ts-and-cs.qmd
        - LICENCE.md
    - title: "Research"
      contents:
        - research/index.qmd
    - title: "Blog"
      contents:
        - blog/index.qmd


  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    left: |
      [Copyright &copy; 2024 Mikkel Roald-Arbøl](/LICENCE.md)
    center:
      - href: https://github.com/roaldarbol
        icon: github
        aria-label: GitHub
      # - href: https://zenodo.org/communities/realworlddatascience
      #   text: "{{< ai zenodo size=2xl >}}"
      #   aria-label: RWDS Zenodo community
      # - href: https://orcid.org/0000-0002-9998-0058
      #   icon: orcid
      #   aria-label: Orcid
      - href: https://www.linkedin.com/showcase/rss-real-world-data-science
        icon: linkedin
        aria-label: LinkedIn
      - href: https://twitter.com/roaldarbol
        icon: twitter-x
        aria-label: Twitter/X
      - href: https://neuromatch.social/@roaldarboel
        icon: mastodon
        aria-label: Mastodon
      - href: feeds.html
        icon: rss
        aria-label: MRA rss

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute:
  freeze: auto
